research_task:
  description: >
    Conduct thorough research on the cybersecurity threats relevant to the organizations software stack. You are provided
    with a high priority vulnerability and information about that vulnerability, along with urls to access more information
    about that vulnerability. 
    Here is the information:
    "cve_id": {cve_id},
    "description": {description},
    "cvss_score": {cvss_score},
    "severity": {severity},
    "date_published": {published},
    "cpe_name": {cpe_name},
    "references": {references}
    Make sure the information is relevant to the last few days.
    Use the Web Scraper tool to gather the necessary information from the urls provided in the references section.
  expected_output: >
    A report on the provided threat, which is relevant to an organizations software stack in a well formatted and concise report.
    The report should include indicators of compromise for the threat and information associated with detecting
    that threat. 
  agent: ctiAnalyst

ranking_task:
  description: >
    Utilize the provided information on threats relevant to an organization and determine which threat is the most
    significant for ensuring security of an organizations network and data.
  expected_output: >
    A report containing the threat name and indicators of compromise associated with that threat. Any other relevant
    information which may be helpful in detecting that threat should also be included. 
  agent: ctiAnalyst

splunk_query_task:
  description: >
    Use the provided information on a threat relevant to our organization to construct a splunk spl
    query for detecting the threat. Step to follow:
    1. Use rag tool to search for relevant sourcetype. ONLY THESE SOURCE TYPES CAN BE USED.
    2. Generate query using relevant sourcetype(s) 
  expected_output: >
    A valid Splunk query and a description of the query. Do not return anything but the splunk spl query 
    and a description of its function. The description should include which threat is being detected.
  agent: cthAnalyst

python_query_task:
  description: >
    Use the provided information on a threat relevant to our organization to construct a python script
    for detecting the threat. Available databases include wineventlog,
    corelight logs, crowdstrike logs, and tanium logs.
  expected_output: >
    A valid python script. Do not return anything but the splunk spl query 
    and a description of its function. The description should include which threat is being detected.
  agent: cthAnalyst

