# Organization Configuration Management Database (CMDB) Configuration
# This file defines the organization's software stack for CPE vulnerability tracking

organization:
  name: "Your Organization"
  description: "Configuration management database for vulnerability tracking"
  
# Software stack components to track for vulnerabilities
software_stack:
  operating_systems:
    - vendor: "microsoft"
      products: ["windows_10", "windows_11", "windows_server_2019", "windows_server_2022"]
    - vendor: "apple"
      products: ["macos"]
    - vendor: "linux"
      products: ["ubuntu", "centos", "red_hat_enterprise_linux", "debian"]
  
  applications:
    - vendor: "microsoft"
      products: ["office", "sharepoint", "teams", "powerpoint", "excel", "onedrive", "onedrive_for_business", "active_directory", "visual_studio", "sql_server", "iis", "exchange_server"]
    - vendor: "oracle"
      products: ["java", "mysql", "oracle_database"]
    - vendor: "apache"
      products: ["http_server", "tomcat", "kafka"]
    - vendor: "python"
      products: ["python"]
    - vendor: "nodejs"
      products: ["node.js"]
    - vendor: "crowdstrike"
      products: ["falcon"]
    - vendor: "splunk"
      products: ["splunk_enterprise", "splunk_universal_forwarder"]
    - vendor: "tanium"
      products: ["tanium_core_platform"]
    - vendor: "corelight"
      products: ["zeek"]
  
  cloud_platforms:
    - vendor: "amazon"
      products: ["aws"]
    - vendor: "microsoft"
      products: ["azure"]
    - vendor: "google"
      products: ["google_cloud_platform"]

# CPE search patterns for automated matching
cpe_patterns:
  # Operating Systems
  - "cpe:2.3:o:microsoft:windows_*"
  - "cpe:2.3:o:apple:macos:*"
  - "cpe:2.3:o:*:linux:*"
  
  # Applications
  - "cpe:2.3:a:microsoft:*"
  - "cpe:2.3:a:oracle:java:*"
  - "cpe:2.3:a:apache:*"
  - "cpe:2.3:a:python:python:*"
  - "cpe:2.3:a:nodejs:node.js:*"
  - "cpe:2.3:a:crowdstrike:*"
  - "cpe:2.3:a:splunk:*"
  - "cpe:2.3:a:tanium:*"
  - "cpe:2.3:a:corelight:*"

# API configuration
api_config:
  base_url: "https://services.nvd.nist.gov/rest/json"
  cpe_endpoint: "/cpes/2.0"
  cve_endpoint: "/cves/2.0"
  results_per_page: 500
  max_retries: 3
  timeout: 30
  
# Update frequency settings
update_settings:
  check_interval_hours: 24
  last_modified_days: 7  # Only check for updates in last 7 days
  enable_auto_updates: true

# Output configuration
output:
  format: "json"  # json, yaml, csv
  include_metadata: true
  include_cpe_details: true
  include_vulnerability_links: true
